//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudWindowsForm.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class datos
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> Fecha_Naciemiento { get; set; }
        public string Estado_Civil { get; set; }
        public string Grado_Academico { get; set; }
        public string Direccion { get; set; }
    }
}
